# -*- coding: utf-8 -*-
"""Parche v3.1 (actualización legal, doc 18) sobre build_content.py: caso 111 «Sin deducción adicional», barra 15 del tornado,
02_Legal (25 normas, cifras en fórmula), 03_Tramites (Registro Ambiental, re-plan, 17 hitos, memo estático), 11 (15 riesgos), 12 (fuentes del
Atlas), 13 (controles F12 y H14). Idempotente: comprueba que cada bloque original existe una sola vez antes de sustituirlo."""
import re, sys

P = "build_content.py"
s = open(P, encoding="utf-8").read()
assert "T_DEDAD" not in s, "el parche ya está aplicado"


def rep(old, new, count=1):
    global s
    assert s.count(old) == count, (old[:100], s.count(old))
    s = s.replace(old, new)


def block(start_marker, end_marker):
    """Devuelve el texto entre el inicio de start_marker y el inicio de end_marker (ambos únicos)."""
    assert s.count(start_marker) == 1 and s.count(end_marker) == 1, (start_marker, end_marker)
    a = s.index(start_marker); b = s.index(end_marker)
    assert a < b
    return s[a:b]


# ------------------------------------------------------------------ índices de casos: tornado ronda 2 + caso 111
rep("# v3.0 (ronda 2): tornado +5 (99–103) y puente v2.0 → v3.0 +6 (104–109) → 110 casos\nT2_START = TX_START + len(PRECIO_STEPS)       # 99\nT_DISP, T_ESCK, T_PKW, T_UG, T_REP = range(T2_START, T2_START + 5)\nBR_START = T2_START + 5                       # 104\nBR0, BR1, BR2, BR3, BR4, BR5 = range(BR_START, BR_START + 6)\nN_CASES = BR_START + 6                        # 110",
    "# v3.0 (ronda 2): tornado +5 (99–103) · v3.1 (doc 18 D-L6): +1 «Sin deducción adicional» (104) · puente v2.0 → v3.0 +6 (105–110) → 111 casos\nT2_START = TX_START + len(PRECIO_STEPS)       # 99\nT_DISP, T_ESCK, T_PKW, T_UG, T_REP, T_DEDAD = range(T2_START, T2_START + 6)\nBR_START = T2_START + 6                       # 105\nBR0, BR1, BR2, BR3, BR4, BR5 = range(BR_START, BR_START + 6)\nN_CASES = BR_START + 6                        # 111")

# ------------------------------------------------------------------ tornado: barra 15
rep("""    ('="Reemplazo de inversores pagado por "&IF(Reemplazo_Pagador="SALELGI","Exergy","SALELGI")', T_REP, None, '="(14) Quién paga el reemplazo en t = "&Reemplazo_Anio&" ("&TEXT(Reemplazo_USD,"#,##0")&" USD): hoy "&Reemplazo_Pagador&"; el alterno mueve la TIR del proyecto "&' + "{DTIR_REP}" + '&" pp y el VAN de Exergy "&TEXT(' + "{VANX_REP}" + '-X_VANX,"+#,##0;-#,##0")&" USD."'),
]""",
    """    ('="Reemplazo de inversores pagado por "&IF(Reemplazo_Pagador="SALELGI","Exergy","SALELGI")', T_REP, None, '="(14) Quién paga el reemplazo en t = "&Reemplazo_Anio&" ("&TEXT(Reemplazo_USD,"#,##0")&" USD): hoy "&Reemplazo_Pagador&"; el alterno mueve la TIR del proyecto "&' + "{DTIR_REP}" + '&" pp y el VAN de Exergy "&TEXT(' + "{VANX_REP}" + '-X_VANX,"+#,##0;-#,##0")&" USD."'),
    # v3.1 (doc 18 D-L6): deducción adicional condicionada a la certificación ambiental previa (RLRTI art. 28 num. 6 lit. g; Atlas P-01)
    ('=IF(Aplica_DedAd="Sí","Sin deducción adicional (sin certificación ambiental)","Con deducción adicional (certificación obtenida)")', T_DEDAD, None,
     f'="(15) La deducción adicional del art. 10.7 LRTI exige certificación ambiental previa a la primera declaración (RLRTI 28.6.g; procedimiento no publicado, Atlas P-01): el caso alterno mueve la TIR del proyecto "&{_dtir(T_DEDAD)}&" pp y la del accionista "&IFERROR(TEXT(({mo(T_DEDAD, "TIR_eq")}-{mo(CASE_X, "TIR_eq")})*100,"+0.0;-0.0"),"n/a")&" pp (escudo anual "&TEXT(MIN(CAPEX_Depreciable*Pct_Elegible_DedAd/Vida_Fiscal_Equipos,Tope_DedAd_Pct*Ingresos_SALELGI)*Tasa_IR,"#,##0")&" USD durante "&Vida_Fiscal_Equipos&" años)."'),
]""")
rep("""'="Peaje "&TEXT(Sens_Peaje_kW,"0.0")&" $/kW-mes"', "Sin absorción fiscal", '="Reemplazo paga "&IF(Reemplazo_Pagador="SALELGI","Exergy","SALELGI")']""",
    """'="Peaje "&TEXT(Sens_Peaje_kW,"0.0")&" $/kW-mes"', "Sin absorción fiscal", '="Reemplazo paga "&IF(Reemplazo_Pagador="SALELGI","Exergy","SALELGI")',
                 '=IF(Aplica_DedAd="Sí","Sin deducción adicional","Con deducción adicional")']""")

# ------------------------------------------------------------------ casos: parámetro dedad y caso 111
rep("""                dec="=Desmantelamiento_Pct", deg="=Degradacion_Adicional")
    B = {k: f"=$B${r}" for k, r in PARAM_ROWS.items()}""",
    """                dec="=Desmantelamiento_Pct", deg="=Degradacion_Adicional",
                # v3.1 (doc 18 D-L6): deducción adicional aplicable (certificación ambiental previa); compartida por los cuatro casos
                dedad='=IF(Aplica_DedAd="Sí",1,0)')
    B = {k: f"=$B${r}" for k, r in PARAM_ROWS.items()}""")
rep("""    cases.append(case("Reemplazo alt.", "Reemplazo pagado por el otro (SALELGI ↔ Exergy; si No → SALELGI)", rep=f"=IF($B${R['rep']}=1,2,1)"))
""",
    """    cases.append(case("Reemplazo alt.", "Reemplazo pagado por el otro (SALELGI ↔ Exergy; si No → SALELGI)", rep=f"=IF($B${R['rep']}=1,2,1)"))
    # v3.1 (doc 18 D-L6): deducción adicional alterna (Sí ↔ No): sin certificación ambiental previa (RLRTI 28.6.g)
    cases.append(case("Sin deducción adicional", "Deducción adicional alterna al Custom (Sí ↔ No): sin la certificación ambiental previa del RLRTI 28.6.g", dedad=f"=1-$B${R['dedad']}"))
""")

# ------------------------------------------------------------------ 02_Legal · matriz normativa (25 filas)
NEW_LEGAL = '''LEGAL_ROWS = [
    ("Régimen habilitante", "Regulación ARCONEL-005/24 codificada (Resol. ARCONEL-010/2024, 27-oct-2024; RO 689, 22-nov-2024 ⚠ fuente secundaria)", "Marco normativo de la GD para autoabastecimiento de consumidores regulados. Cadena 003/18 → 001/21 → 008/23 → 005/24: deroga la ARCERNNR-008/23 (techo 2 MW); la 002/21 (empresas generadoras en GD) fue derogada por la ARCONEL-006/24 (Resol. 011/2024, 27-oct-2024). Sin reformas hasta la Resol. ARCONEL-008/26 (02-sep-2026).", "El SGDA de GPM se habilita ante CNEL EP (distribuidora), sin título ministerial. No citar 002/21 ni 008/23.", "Vigente · Atlas N7bis/N6 · verificada 08-sep-2026", "Alta"),
    ("Modalidad", "Art. 10.3 — modalidad 2a (individual remoto)", "«El SGDA está ubicado remotamente, y está asociado a una sola cuenta contrato del Consumidor Regulado.»", "Planta en Montecristi ↔ cuenta contrato 201013346360 (SALELGI, Machala).", "Vigente · verbatim (Auditoría Fases 1–2, 07-sep-2026)", "Alta"),
    ("Ubicación remota entre unidades de negocio", "Art. 6 lit. c) + nota 1 (codificada)", "«Encontrarse ubicado dentro de la misma Área de Servicio de la Distribuidora en la que se encuentran sus consumidores» — nota 1: «O entre unidades de negocio de CNEL EP.» La nota 1 ya existía en la versión original (Resol. 008/2024); la codificación (Resol. 010/2024) eliminó el lit. d) que exigía la misma unidad de negocio.", "Montecristi (U.N. Manabí) → Machala (U.N. El Oro) PERMITIDO: ambas son CNEL EP. Duda operativa abierta (sin fuente): qué U.N. tramita y cómo se liquida el crédito → consulta escrita a CNEL EP antes de la factibilidad.", "Vigente · Auditoría D-05 · Atlas · 08-sep-2026", "Alta"),
    ("Potencia", "Art. 7 lit. a)", "«Si hay inyección… la Potencia Nominal de un SGDA estará limitada a la capacidad de la red en el punto de conexión aprobada por la Distribuidora.» Sin techo de MW en el articulado («2 MW» solo topa el rubro).", '="La capacidad del alimentador de Montecristi para "&TEXT(Potencia_AC,"#,##0")&" kWac en 13,8 kV (flujo inverso ≤ 60 % nominal, manual CNEL) es el riesgo binario. Evidencia: CENACE sitúa Manta entre las subestaciones al límite (Expreso, 30-jun-2026); refuerzos de 6–18 meses (Expreso, 20-ago-2026) → pre-consulta escrita de capacidad (RC-00) y factibilidad (RC-09)."', "Vigente · verbatim (S5) · evidencia de red: prensa (M)", "Alta / Media (red)"),
    ("Energía", "Art. 9", "«La producción anual de energía del SGDA deberá ser igual o menor que la demanda de energía anual de los Consumidores Regulados» (24 meses de consumos para consumidores existentes).", f'="Año 1 (P50): "&TEXT(\\'{S4}\\'!${C(1)}${ENERGIA["p50"]},"#,##0")&" MWh ≤ "&TEXT(Consumo_Anual/1000,"#,##0")&" MWh de demanda ("&TEXT(\\'{S4}\\'!${C(1)}${ENERGIA["p50"]}/(Consumo_Anual/1000),"0%")&") — margen amplio; potencia máxima teórica ≈ "&TEXT(Consumo_Anual/Yield_Ref/F_Recorte/1000,"0.0")&" MWp."', "Vigente · verificado · cifras en fórmula (v3.1)", "Alta"),
    ("Titularidad y rol de Exergy", "Art. 8 lit. a) y b) 005/24 · art. innumerado tras el art. 44 LOSPEE (texto de la Ley 2026, art. 23; antes LOCE 2024)", "El consumidor puede ser propietario (declaración juramentada) aunque un tercero financie; puede contratar a terceros «para el financiamiento, gestión, operación, vigilancia, instalación, mantenimiento y desmantelamiento». LOSPEE (Ley 2026, art. 23): «Los consumidores regulados y no regulados podrán instalar sistemas de generación exclusivamente para su autoabastecimiento, conectados a la red de distribución o transmisión…» — mantiene la propiedad de terceros, la tercerización y el principio de exclusividad de comercialización. «El instrumento legal… no podrá establecer la actividad de comercialización (compra o venta) de la energía… esto deberá ser verificado por la Distribuidora.»", "SALELGI dueña (art. 8a); Exergy = gerencia + O&M (+ arriendo del terreno si es la propietaria) a renta fija; jamás precio por kWh (revocatoria). La Ley 2026 está en litigio constitucional (14 demandas, 1 admitida, sin sentencia a jun-2026): si cayera vuelve el texto LOCE 2024, que ya habilitaba a terceros → el encaje NO depende de la Ley 2026.", "Vigente · Auditoría D-09 · Atlas N1/N3b · 08-sep-2026", "Alta"),
    ("Prohibición de venta", "Disp. General Décima", "«Bajo ninguna de las modalidades… los propietarios del SGDA (Consumidores Regulados o terceros) o el Representante Legal podrán comercializar energía eléctrica.»", "Los contratos Exergy–SALELGI se redactan como servicios/arriendo con renta fija indexable (no a kWh). Blindaje: arriendo en escritura separada; O&M por kWp-año o disponibilidad; gerencia por hitos; consulta DG 17.ª ante duda.", "Vigente · verbatim (Auditoría) · 08-sep-2026", "Alta"),
    ("Mecanismo de excedentes", "Arts. 26-27 (27.3 para tarifas con demanda horaria)", "Balance mensual: si generación > consumo → Crédito de Energía (kWh) acumulado en SEA/SEEA y debitado en meses deficitarios; «cada 24 meses el SEEA se reiniciará a cero, sin que la Distribuidora deba otorgar una compensación económica». El remanente se valora a Tm (mayor cargo) sólo en tarifa horaria (27.3); en residencial/general, a la tarifa correspondiente (27.1–27.2).", "GPM consume cada mes 755–990 MWh vs 457–612 MWh generados → nunca hay excedente mensual: toda la energía se netea el mismo mes y la bolsa de 24 meses no se usa (04_Energia). SALELGI es tarifa horaria: el excedente de bloque A en meses de bajo consumo se netea como energía equivalente (conserva valor).", "Vigente · verbatim (S2/S5) · Atlas corrección v1.1 · 08-sep-2026", "Alta"),
    ("Qué se netea y qué no", "Arts. 27.2-27.3 y 29", "Solo el cargo por energía. Se siguen pagando cargo por demanda (USD/kW × FGD), comercialización, SAPG y cargos de terceros sobre la energía facturable.", "El modelo NO asume ahorro en demanda (remoto), comercialización ni alumbrado. Tarifa evitable = 0,113 (bloques A/B) y 0,105 (bloque C) ponderados por la inyección horaria ≈ 0,1127 $/kWh. Efecto FGD (Auditoría D-11): un SGDA en sitio puede bajar la demanda media y encarecer el cargo por demanda; en la modalidad remota 2a la demanda medida de GPM no cambia → no aplica.", "Vigente · verificado · 08-sep-2026", "Alta"),
    ("Medición", "Art. 25 y 28 · Anexo F · Regulación ARCONEL-008/24 (Resol. 015/2024, 15-nov-2024; sucede a la 001/20) · calidad: ARCONEL-009/24", "Modalidades remotas: medidor en el punto de entrega del consumidor + medidor (uni/bidireccional) en el punto de conexión del SGDA, a costo del consumidor; −2 % si se mide en el secundario del transformador.", "Medición comercial en 13,8 kV (lado MT) para evitar el descuento del 2 %. Costo del medidor en CAPEX (rubro conexión).", "Vigente · arts. 25/28 verbatim (Auditoría D-14) · Atlas N17/N18 (M)", "Alta / Media (regulación de medición)"),
    ("Peaje de red", "Disp. Transitoria Cuarta 005/24 · RLOCE (D.E. 176, RO 28-feb-2024) art. 18 y DT 16.ª (arts. 5 y 24: definición de peajes — verificar en el PDF)", "RLOCE: los SGDA «pagarán cargos por el uso o disponibilidad de la red de distribución, según la regulación» de ARCONEL; peaje de distribución = «valores por potencia y energía» (005/24 art. 5.17). 005/24 DT Cuarta: los SGDA pagan peajes «desde el 28 de febrero de 2029». D.E. 176 DT 16.ª: 5 años desde su expedición (23-feb-2029); prevalece la fecha regulatoria.", "Obligación cierta, valor no publicado. Con COD 2028-H2 el peaje llega en el año 1-2 de operación → sensibilidad 0,5/1,0/1,5 ¢/kWh y 0,5–1,0 $/kW-mes (10_Sensibilidad). Cláusula de reapertura en contratos.", "Vigente · fecha Alta (Auditoría D-07) · monto no publicado", "Alta / Baja"),
    ("Trámite y costo", "Arts. 12-16 · CNEL (Cat. 2 > 100 kW)", "Factibilidad de Conexión (17-22 días; vigencia 6 meses en Cat. 2; carta a la máxima autoridad de la U.N. con proyectista registrado en el portal CNEL) → pago USD 4/kW con tope USD 10.000 (> 2 MW) → Certificado de Habilitación (≈ 18 días; vigencia = vida útil, FV 25 años) → obra según cronograma → pruebas (5 días) → medidor MT (≤ 30 días) → Contrato de Conexión (Anexo C) + Contrato de Suministro (inicia el reloj de 24 meses del SEA). > 1 MW: estudios de estabilidad. Sin garantía/póliza.", "Trámite eléctrico rápido (3-6 meses reales); incumplir el cronograma sin justificación = revocatoria (art. 16). La factibilidad vence a los 6 meses: preparar el expediente de habilitación durante la factibilidad (03, control F12).", "Vigente · Atlas hitos 7/11/14/15 · 08-sep-2026", "Alta"),
    ("Obligación de autogenerar (cliente AV1)", "Decreto Ejecutivo 32 (15-jun-2025; RO Supl. 62, 18-jun-2025) — reforma RGLOSPEE, DT 14.ª", "Clientes con tarifa AV1 (167) y AV2 (4) deben instalar generación para abastecer su demanda en 18 meses desde la vigencia del decreto → 18-dic-2026 (la prensa dice 15-dic); CENACE puede ordenar su desconexión en períodos de déficit. Seguimiento: oficio MAE-VEER-2026-0255-OF (7-jul-2026); reportes mensuales de las distribuidoras al Viceministerio desde jul-2026 (Expreso, 23-jul-2026).", '="GPM es AV1 → muy probablemente obligado (confirmar notificación de CNEL El Oro). El proyecto (COD "&TEXT(Fecha_COD,"yyyy")&") NO llega al plazo: su valor es acreditar un proyecto en curso. "&TEXT(Potencia_DC/1000,"0")&" MWp cubren ≈ "&TEXT(Cobertura_Anual,"0%")&" de la demanda; la regla de cumplimiento (total/parcial) la debe definir ARCONEL."', "Vigente · plazo: RO Supl. 62 (Atlas N12 · A) · seguimiento: prensa (M)", "Alta (plazo) / Baja (mecánica)"),
    ("Impuesto a la Renta y participación", "LRTI art. 37 · Código del Trabajo art. 97", "IR 25 %. Participación laboral 15 % sobre utilidades. Sin exoneración de IR aplicable a un SGDA de autoabastecimiento: la LOCE (2024) no la creó (Atlas I-05); el estado 2026 del art. 9.1 LRTI está por verificar.", "El ahorro eleva la utilidad de SALELGI → tasa efectiva marginal 36,25 %. Los libros previos omitían la participación.", "Vigente · Atlas F1/I-05 · art. 9.1 ❓", "Alta / ❓ (art. 9.1)"),
    ("Deducción adicional 100 % (doble depreciación)", "LRTI art. 10 num. 7 (LOCE, RO 2S 475, 11-ene-2024) · RLRTI art. 28 num. 6 lit. g (D.E. 176 art. 78)", "«…sistemas de generación distribuida para autoabastecimiento a base de energías renovables no convencionales… se deducirán con el 100 % adicional… Este gasto adicional no podrá superar un valor equivalente al 5 % de los ingresos totales.» Requisito: certificación de la Autoridad Ambiental Competente ANTES de la primera declaración que la aplique (RLRTI 28.6.g); procedimiento no publicado (Atlas P-01). La adquisición no debe ser exigida por la autoridad ambiental como condición.", f'="Aplica a SALELGI (el art. 10.7 nombra a los SGDA). Con ingresos de "&TEXT(Ingresos_SALELGI/1000000,"0.0")&" M el tope ("&TEXT(Tope_DedAd_Pct*Ingresos_SALELGI/1000,"#,##0")&" k$) "&IF(CAPEX_Depreciable*Pct_Elegible_DedAd/Vida_Fiscal_Equipos>Tope_DedAd_Pct*Ingresos_SALELGI,"muerde","no muerde")&". Aplica_DedAd = "&Aplica_DedAd&"; el caso alterno (10 §B) da TIR "&TEXT({mo(T_DEDAD, "TIR")},"0.00%")&" frente a "&TEXT(X_TIR,"0.00%")&". El exceso sobre el tope se pierde en el modelo (¿diferible? P-14)."', "Vigente · tope confirmado (Atlas I-02; errata v1.1 Informe F3) · certificación ❓ (P-01)", "Alta (tope) / Media (certificación)"),
    ("IVA", "LRTI art. 65 (15 %) · art. 55 num. 19 (0 % FV, LOCE) · art. 66 (crédito tributario)", "IVA 15 % general (art. 65); 0 % para «paneles solares… y accesorios para la generación solar fotovoltaica» — código Ecuapass 0719 (boletín SENAE 15-ene-2024); el alcance de «accesorios» es indefinido (inversores, estructuras, cables, transformadores). Crédito tributario si hay ventas gravadas (art. 66).", '="SALELGI factura arriendos gravados → el IVA del CAPEX ("&TEXT(IVA_Total/1000000,"0.00")&" M) es crédito recuperable (capital de trabajo), no costo. Inversores a 0 %: ZONA GRIS (Atlas P-04; decisión D-L5) → resolución anticipada de clasificación SENAE; estructura y BOS a 15 %."', "Vigente · Atlas F1/I-12/P-04 (texto del art. 65 no cotejado: M)", "Alta / Media (alcance)"),
    ("ISD y aranceles", "Ley Reformatoria para la Equidad Tributaria art. 159 · RAISD art. 17.1 · Arancel del Ecuador (COMEX; D.E. 272 y Acuerdo MPCEI-2026-0003-A) · COPCI", "ISD 5 % sobre pagos al exterior (sin crédito tributario); tarifas diferenciadas 2026 sin partidas FV. Módulos 8541.43: 0 %; inversores 8504.40 ≈ 5 %; estructuras 7308.90.90: 20 %; trafos 8504.22 ≈ 11,25 %; FODINFA 0,5 %. Exención de ISD en bienes de capital sólo con Contrato de Inversión con anexo de subpartidas (RAISD 17.1); techo de gasto tributario 2026 desconocido (2025: USD 60 MM «por única ocasión», P-02). Arancel 2026 no cotejado (P-03); COMEX 002-2025 (0 % temporal) vencida el 31-dic-2025 sin prórroga localizada.", '="≈ "&TEXT(Aranceles_ISD/1000,"#,##0")&" k$ de arancel + ISD en el caso activo (05_CAPEX). Toggle Contrato_Inversion. La reducción de −5 pts de IR NO aplica a SALELGI (no es sociedad nueva). Duda #19: ¿autoconsumo = inversión productiva? Aranceles de 05 marcados «por confirmar (P-03)»."', "Vigente · Atlas I-15/I-16/I-19/I-20 · ADV pendiente SENAE", "Media"),
    ("Partes relacionadas", "LRTI art. 4.1 / RALRTI (precios de transferencia)", "Operaciones con partes relacionadas > USD 3 M/ejercicio → Anexo OPR; > 15 M → Informe Integral. Deben pactarse a valor de mercado.", '="EPC/gerencia (≈ "&TEXT(CAPEX_Total/1000000,"0.0")&" M) y O&M"&IF(Comprador_Terreno="Exergy"," y arriendo","")&" Exergy–SALELGI: documentar comparables (fee "&TEXT(Fee_Gerencia_Pct,"0%")&IF(Comprador_Terreno="Exergy",", arriendo "&TEXT(Renta_Terreno_ha,"#,##0")&" $/ha","")&", O&M "&TEXT(Fee_OM_kWp,"0")&" $/kWp). Las retenciones 2026 (fila siguiente) son anticipos del IR de Exergy."', "Vigente · 08-sep-2026", "Media"),
    ("Retenciones en la fuente 2026 (Exergy)", "Resol. SRI NAC-DGERCGC26-00000009 (27-feb-2026; vigente desde 01-mar-2026)", "Porcentajes de retención: construcción/obra 2 % · servicios prestados por sociedades 5 % · arrendamiento de inmuebles 10 % · transferencia de bienes 2 %.", "SALELGI retiene a Exergy en cada factura (gerencia y O&M 5 %; arriendo 10 % si Exergy es la dueña del terreno): anticipos del IR de Exergy (no costo), pero adelantan caja. No afecta el flujo de SALELGI (interno).", "Vigente · Atlas F2 · 08-sep-2026", "Alta"),
    ("Ambiental", "COA + RCOA · Resol. MAATE-2025-0002-R (22-abr-2025) · Resol. ARCONEL-005/25 (RO Supl. 67, 25-jun-2025): arts. 19–22 (Registro) y 23–35 (Licencia) · A.M. 083-B (tasas)", "Autoridad Ambiental Competente del sector eléctrico = ARCONEL (Unidad Técnica Ambiental) desde may-2025, vía SUIA. FV > 1 y ≤ 10 MW → Registro Ambiental: automático en la norma, USD 180 (+ USD 80), sin consultor calificado, 5–6 meses observados en otros sectores. Licencia Ambiental (75 + 15 + 15 días, EIA, participación ciudadana, póliza 100 % del PMA; 1 ‰ del proyecto, mín. USD 500/1.000) sólo > 10 MW o interés nacional / SNAP (MAATE). Umbrales del CCAN en SUIA por confirmar (P-06).", "Base = Registro Ambiental (RC-04, meses 3–8; decisión D-L1). La «unidad de proyecto» de las 10,78 ha (2 × 5 MWp = 10,0 MWp DC / 7,6 MWac) queda como riesgo documentado (11) y contingencia: Licencia = +3 meses y ≈ +70 k (memo de 03).", "Vigente · Atlas N22 (A) · plazos observados (M)", "Alta (ruta) / Media (plazo)"),
    ("Institucional", "D.E. 256 (ARCONEL) · D.E. 94 (Ministerio de Ambiente y Energía) · D.E. 376 (ministro J.C. Blum, 7-may-2026) · Resol. MAATE-2025-0002-R", "Regulador: ARCONEL — además Autoridad Ambiental Competente del sector eléctrico (UTA). Rector: Ministerio de Ambiente y Energía. Ventanilla del SGDA: CNEL EP.", "Citar sólo entidades vigentes; el trámite ambiental no va al Ministerio sino a ARCONEL (SUIA).", "Vigente · Atlas instituciones · 08-sep-2026", "Alta"),
    ("Ley de Sectores Estratégicos 2026", "Ley Orgánica para el Fortalecimiento de los Sectores Estratégicos de Minería y Energía (RO 5.º Supl. 234, 02-mar-2026)", "Vigente pero no operativa: sin reglamento, sin cupo anual (art. 25.1) ni regulación del DAE. Refuerza la propiedad y los servicios de terceros en autoabastecimiento (art. 23: texto nuevo del art. innumerado tras el 44 LOSPEE); excluye de la reversión los bienes del usuario final (art. 33); despacho preferente para ERNC ≤ 10 MW (art. 48). Litigio constitucional: 14 demandas, 1 admitida, sin medidas cautelares ni sentencia (El Universo, 06-jun-2026).", "Contexto favorable pero no necesario: el encaje SALELGI–Exergy se sostiene en la 005/24 y en el texto LOCE 2024 si la Ley cayera. Monitorear reglamento y sentencia (P-13).", "Vigente-no-operativa · Atlas N3b · 08-sep-2026", "Alta"),
    ("Sentencia de la Corte Constitucional", "Sentencia 112-21-IN/25 (11-dic-2025)", "Declara la inconstitucionalidad del num. 1 del art. 25 LOSPEE (texto 2021) con efectos a futuro; no paraliza proyectos; valida la figura del autogenerador. Superada por la sustitución del art. 25 en la Ley 2026.", "Sin efecto directo sobre un SGDA de consumidor regulado; contexto del marco y del litigio de la Ley 2026.", "Ejecutoriada · Atlas N19 · 08-sep-2026", "Alta"),
    ("Uso de suelo rural del predio", "LOTRTA art. 6 y art. 32 lit. l · Reglamento LOTRTA art. 3 · COOTAD / LOOTUGS (PUGS Montecristi)", "Si el predio es agrícola, el GAD solicita al MAG el informe técnico de no aptitud agropecuaria (90 días) para declararlo zona industrial / de infraestructura; la compatibilidad de uso la certifica el GAD (línea de fábrica).", "Clasificación catastral/PDOT del predio POR CONFIRMAR (P-07): si es agrícola, +4 meses (RC-08b) antes del permiso de construcción. Verificar antes de comprar (RC-01).", "Vigente · Atlas K1 · 08-sep-2026", "Alta (norma) / ❓ (predio)"),
    ("Servidumbre de la línea y altura", "Regulación ARCONEL-001/18 (franjas de servidumbre) · RDAC 154 Enmienda 3 (jun-2024)", "Franja de servidumbre de 6 m para líneas de V ≤ 13,8 kV. Aeronáutica: consulta de altura caso por caso ante la DGAC; no exige estudio de deslumbramiento.", "La línea 13,8 kV al punto de conexión requiere franja y, si cruza vías, permisos de Prefectura/MTOP/GAD (RC-15, «por confirmar»). ¿Resolución ministerial para la servidumbre de una línea privada de SGDA o basta el diseño aprobado por CNEL? ❓", "Vigente · Atlas N23/K2 · 08-sep-2026", "Alta / ❓ (línea privada)"),
]
'''
old = block("LEGAL_ROWS = [", "CANDADOS = [")
s = s.replace(old, NEW_LEGAL)

NEW_CANDADOS = '''CANDADOS = [
    ("1 · Régimen", "SGDA 005/24 codificada · modalidad 2a remota entre unidades de negocio de CNEL EP", '="● Habilitado (Res. ARCONEL-005/24 codificada; sin reformas a sep-2026)"', "ok"),
    ("2 · Energía (art. 9)", "Producción anual ≤ demanda anual del consumidor", f"=IF('{S4}'!${C(1)}${ENERGIA['p50']}<=Consumo_Anual/1000,\\"● \\"&TEXT('{S4}'!${C(1)}${ENERGIA['p50']}/(Consumo_Anual/1000),\\"0%\\")&\\" de la demanda\\",\\"■ excede: \\"&TEXT('{S4}'!${C(1)}${ENERGIA['norec']},\\"#,##0\\")&\\" MWh no reconocidos\\")", "ok"),
    ("3 · Comercial (art. 8 / Décima / LOSPEE art. innumerado tras el 44)", "Exergy cobra servicios y arriendo a renta fija — nunca $/kWh (exclusividad de comercialización)", '="● Sin venta de kWh · blindaje: arriendo en escritura separada, O&M por kWp-año, gerencia por hitos; consulta DG 17.ª ante duda"', "ok"),
    ("4 · Físico (art. 7a)", '="Capacidad del alimentador 13,8 kV para "&TEXT(Potencia_AC,"#,##0")&" kWac (aprobable: "&TEXT(Capacidad_Alimentador_kW,"#,##0")&" kW, por confirmar)"', '=IF(Potencia_AC>Capacidad_Alimentador_kW,"■ Potencia AC supera la capacidad por confirmar del alimentador","▲ Pendiente: pre-consulta escrita de capacidad (RC-00) + factibilidad CNEL (RC-09) — Manta al límite (CENACE, 30-jun-2026)")', "warn"),
    ("5 · Económico (Disp. Trans. Cuarta)", '="Peaje de red desde "&TEXT(Fecha_Peaje,"dd-mmm-yyyy")&" — valor no publicado (por potencia y energía)"', '="▲ Sensibilizado 0–"&TEXT(Sens_Peaje*100,"0.0")&" ¢/kWh y "&TEXT(Sens_Peaje_kW,"0.0")&" $/kW-mes (activo: "&TEXT(Eff_Peaje*100,"0.0")&" ¢ · "&TEXT(Peaje_kW_mes,"0.00")&" $/kW-mes)"', "warn"),
]
'''
old = block("CANDADOS = [", "CONTRATOS = [")
s = s.replace(old, NEW_CANDADOS)

NEW_CONTRATOS = '''CONTRATOS = [
    ("Contrato de gerencia y desarrollo del proyecto", "Exergy → SALELGI", '="Fee "&TEXT(Fee_Gerencia_Pct,"0%")&" del valor del proyecto (hitos 30/70). Alcance: ingeniería de dueño, permisos, procura multi-contrato, supervisión, puesta en marcha."', "Partes relacionadas: documentar comparables. Retención 5 % (servicios) como anticipo del IR de Exergy; IVA 15 %."),
    ("Contratos de suministro e instalación (multi-contrato)", "Proveedores → SALELGI", "Módulos, inversores, estructura, CT/MT, BOS, obra civil, montaje, conexión. SALELGI importa (ISD/arancel a su cargo) o compra DDP.", "Sin margen EPC integrado; riesgo de integración lo gestiona Exergy. IVA: bienes FV 0 % (código 0719) y servicios 15 %, desglosados en la facturación."),
    ('="Contrato de arriendo / usufructo del terreno ("&TEXT(Hectareas,"0.0")&" ha)"', "Exergy → SALELGI", '=IF(Comprador_Terreno="SALELGI","No aplica en el caso activo: SALELGI compra el terreno (Comprador_Terreno). Si Exergy comprara: renta fija "&TEXT(Renta_Terreno_ha,"#,##0")&" $/ha-año indexada ("&TEXT(Escalacion_OPEX,"0.0%")&"/año), plazo ≥ 25 años, escritura separada del EPC/gerencia/O&M, figura inscribible y oponible ≥ plazo del crédito.","Renta fija "&TEXT(Renta_Terreno_ha,"#,##0")&" $/ha-año indexada ("&TEXT(Escalacion_OPEX,"0.0%")&"/año), plazo ≥ 25 años (vida útil del certificado), en escritura separada del EPC/gerencia/O&M; figura inscribible y oponible por plazo ≥ al del crédito (usufructo o derecho de superficie; figura óptima por confirmar, P-12).")', "Arrendamiento/posesión notariado = documento del Certificado de Habilitación (005/24 art. 15 lit. a.2). Retención 10 % (arriendo)."),
    ("Contrato de O&M", "Exergy → SALELGI", '="Fee fijo "&TEXT(Fee_OM_kWp,"0")&" $/kWp-año indexado ("&TEXT(Escalacion_OPEX,"0.0%")&"/año) o por disponibilidad garantizada (SLA "&TEXT(Disponibilidad,"0%")&"); incluye limpieza, seguridad, monitoreo, repuestos y reserva de inversores."', "Renta fija: no indexar a kWh producidos (recaracterización). Cláusula de reemplazo de inversores: quién paga (10 §G.2)."),
    ("Declaración juramentada de propiedad del SGDA", "SALELGI → CNEL", "Art. 8 lit. a) 005/24: SALELGI acredita ser dueña aunque el proyecto lo gerencie/financie un tercero.", "Previo al inicio de operación."),
    ("Pre-consulta de capacidad + Factibilidad de Conexión + Certificado de Habilitación + Contrato de Conexión (Anexo C) + Contrato de Suministro", "SALELGI ↔ CNEL EP (U.N. Manabí / El Oro)", "Carta a la máxima autoridad de la U.N. con proyectista registrado en el portal CNEL; Cat. 2, > 1 MW: estudios de estabilidad; factibilidad 17–22 días (vigencia 6 meses); rubro USD 4/kW ≤ 10.000; certificado ≈ 18 días; medidor bidireccional MT; el Contrato de Suministro inicia el reloj de 24 meses del SEA.", "Confirmar la U.N. competente para el trámite remoto inter-U.N.; preparar el expediente de habilitación durante la factibilidad (vigencia 6 meses; control F12)."),
    ("Consulta a la Administración de ARCONEL (Disp. General 17.ª) — opcional", "SALELGI / Exergy → ARCONEL", "«Los casos especiales… serán resueltos por la Administración de la ARCONEL»: vía para obtener certeza sobre el esquema de terceros (arriendo + gerencia + O&M) y la agregación inter-U.N. antes de firmar.", "Sin precedentes públicos de recaracterización (P-11); la consulta reduce el riesgo contractual (11)."),
    ("Contrato de crédito (si aplica)", "Banco → SALELGI", "Corporativo: garantía real sobre el SGDA + cesión de flujos/contratos + cuenta de reserva; DSCR ≥ 1,2x exigible.", "Ver 08_Flujo bloque B y 10 §D/§H. Líneas verdes: BanEcuador 11,86 % (PYME), Produbanco hasta 84 meses (Atlas J)."),
]
'''
old = block("CONTRATOS = [", "DUDAS = [")
s = s.replace(old, NEW_CONTRATOS)

NEW_DUDAS = '''DUDAS = [("#9 · P-08", "Capacidad real del alimentador 13,8 kV Montecristi (flujo inverso ≤ 60 %); Manta entre las subestaciones al límite (CENACE, 30-jun-2026)", "Binario para inyectar 3,8 MWac; refuerzos de 6–18 meses (Expreso, 20-ago-2026)", "Pre-consulta escrita de capacidad a CNEL EP U.N. Manabí (RC-00) + Factibilidad de Conexión (RC-09)", "Alta"),
         ("#8 · P-06", "«Unidad de proyecto» ambiental por las 10,78 ha (2 × 5 MWp): Registro (≤ 10 MW) o Licencia (> 10 MW); umbrales del CCAN en SUIA", "±3–6 meses de cronograma y ≈ 70 k (memo de 03)", "Consulta a ARCONEL — Unidad Técnica Ambiental (SUIA), no al Ministerio", "Alta"),
         ("Nueva", "Trámite remoto inter-U.N.: qué unidad de negocio de CNEL tramita y cómo se liquida el crédito entre Manabí y El Oro", "Operativa de facturación (el encaje legal está confirmado: art. 6 nota 1)", "Consulta escrita a CNEL EP (Gerencia Comercial)", "Alta"),
         ("Nueva", "D.E. 32: ¿SALELGI fue notificada como cliente AV1 obligado? ¿Cómo se acredita cumplimiento parcial y un proyecto en curso al 18-dic-2026?", "Riesgo de desconexión en déficit; narrativa del proyecto", "CNEL El Oro / Viceministerio de Electricidad (oficio MAE-VEER-2026-0255-OF; reportes mensuales desde jul-2026)", "Alta"),
         ("#17 → P-01 / P-14", "Certificación ambiental previa para la deducción adicional (RLRTI 28.6.g): procedimiento y autoridad no publicados; ¿el exceso sobre el tope del 5 % se pierde o se difiere?", f'="Sin certificación no hay deducción: TIR "&TEXT(X_TIR,"0.00%")&" → "&TEXT({mo(T_DEDAD, "TIR")},"0.00%")&"; accionista "&TEXT(X_TIReq,"0.0%")&" → "&TEXT({mo(T_DEDAD, "TIR_eq")},"0.0%")&" (10 §B)"', "Consulta a ARCONEL (autoridad ambiental del sector) + consulta vinculante SRI", "Alta"),
         ("#18 → P-04", "Alcance del IVA 0 % «accesorios para la generación solar FV» (inversores, estructura, BOS)", "Capital de trabajo (recuperable): −0,01 pp de TIR si los inversores fueran 15 %", "Resolución anticipada de clasificación arancelaria SENAE (código 0719)", "Media"),
         ("#19 → P-02", "¿SGDA de autoconsumo califica como «inversión productiva» (Contrato de Inversión)? Techo de gasto tributario 2026 y cupo renovables (2025: USD 60 MM «por única ocasión»)", '="≈ "&TEXT(Aranceles_ISD/1000,"#,##0")&" k$ de arancel + ISD (caso activo)"', "CEPAI / MPCEI", "Media"),
         ("#23 → P-11", "Estructura de arriendo y O&M a renta fija (anti-recaracterización): sin precedentes públicos; la Ley 2026 legaliza expresamente a terceros", "Conserva el certificado", "Abogado eléctrico + revisión previa de la Distribuidora (art. 8b) + consulta DG 17.ª", "Alta"),
         ("Nueva · P-13", "Litigio constitucional de la Ley 2026 (14 demandas, 1 admitida, sin sentencia a jun-2026): efecto en cascada sobre arts. 25/25.1, DAE y art. 3", "Contexto: el encaje del esquema no depende de la Ley 2026", "Monitoreo de la Corte Constitucional y del reglamento", "Alta"),
         ("Nueva · P-07", "Clasificación catastral/PDOT del predio: si es agrícola → cambio de uso de suelo rural (LOTRTA art. 6: informe MAG 90 días + GAD)", "+4 meses antes del permiso de construcción (RC-08b)", "Certificado de uso de suelo del GAD Montecristi antes de comprar (RC-01)", "Alta"),
         ("Nueva · P-12", "Figura inscribible del derecho de SALELGI sobre el terreno de Exergy (arriendo / usufructo / superficie), oponible por plazo ≥ al del crédito", "Bancabilidad y documento de posesión (005/24 art. 15 a.2); no aplica si SALELGI compra", "Abogado inmobiliario + Registro de la Propiedad Montecristi", "Alta"),
         ("Nueva", "Vías y derecho de vía de la línea 13,8 kV: clasificación de la vía (Prefectura de Manabí / MTOP / GAD) y permisos de cruce", "Costo y plazo de RC-15 «por confirmar»", "Consulta a Prefectura/MTOP/GAD con el trazado de RC-14", "Media"),
         ("Nueva", "Servidumbre de la línea privada del SGDA: ¿resolución ministerial o basta el diseño aprobado por CNEL? (ARCONEL-001/18: franja 6 m a ≤ 13,8 kV)", "Trámite adicional potencial", "CNEL EP U.N. Manabí / Ministerio de Ambiente y Energía", "Media"),
         ("Nueva · P-09", "Textos ilegibles: Resol. ARCONEL-005/26 (codificación del Código de Conexión) publicada sin capa de texto; reglamento de la Ley 2026 pendiente", "Requisitos técnicos de conexión y régimen de excedentes", "Monitoreo ARCONEL / RO; pedir versión editable", "Media"),
         ("Resuelta", "Fecha exacta del plazo del D.E. 32: 18-dic-2026 (18 meses desde el RO Supl. 62, 18-jun-2025; la prensa dice 15-dic)", "Precisión citacional", "Registro Oficial Supl. 62 (Atlas N12)", "Baja")]
'''
old = block("DUDAS = [", "\n\ndef table_rows")
s = s.replace(old, NEW_DUDAS.rstrip("\n"))
rep('section(ws, r, 2, 7, "Zonas grises vivas (con dueño y urgencia) — registro de dudas del Informe Maestro")',
    'section(ws, r, 2, 7, "Zonas grises vivas (con dueño y urgencia) — dudas del Informe Maestro y pendientes P-xx del Atlas Regulatorio v2.0")')
rep('sheet_header(ws, "2 · Marco legal y regulatorio", "Lo que habilita, lo que limita y cómo se estructura; investigación de decisión, no opinión legal. Sustenta los supuestos regulatorios de 01, los candados de 13 y los riesgos de 11 (fuentes en 12 §D).", 2, last_col=7)',
    'sheet_header(ws, "2 · Marco legal y regulatorio", "Lo que habilita, lo que limita y cómo se estructura; investigación de decisión, no opinión legal. Conciliado con el Atlas Regulatorio FV Ecuador v2.0 (sello 08-sep-2026). Sustenta los supuestos regulatorios de 01, los candados de 13 y los riesgos de 11 (fuentes en 12 §D).", 2, last_col=7)')

# ------------------------------------------------------------------ 03_Tramites · 17 hitos (Registro Ambiental, pre-consulta, re-plan)
NEW_TRAMITES = '''TRAMITES = [
    ("RC-00", "Consultas previas: pre-consulta escrita de capacidad en 13,8 kV a CNEL EP U.N. Manabí (1–2 semanas), SRI (art. 10.7 y 55.19), CEPAI (contrato de inversión), CNEL (trámite remoto inter-U.N.), consulta arancelaria", "CNEL EP · SRI · MPCEI · SENAE", "005/24 · LRTI · COPCI", 1, 3, 15000, "—", "No", "Medio", "La pre-consulta anticipa refuerzos de red (Manta al límite, CENACE 30-jun-2026); las consultas definen el caso fiscal y la operativa del crédito."),
    ("RC-01", "Control del predio: compra de 5 ha + verificación registral y catastral del uso de suelo (PDOT/PUGS) + figura inscribible a SALELGI (arriendo / usufructo / superficie) si compra Exergy", "Notaría · Registro de la Propiedad · GAD Montecristi", "Código Civil · LOTRTA art. 6 · COOTAD", 1, 3, 8000, "—", "Sí", "Medio", "Documento de posesión para CNEL (art. 15 a.2). Si el predio es agrícola → RC-08b. Figura óptima por confirmar (P-12)."),
    ("RC-02", "Debida diligencia registral, topografía y geotecnia (hincado, corrosividad)", "Consultores", "—", 1, 2, 25000, "—", "No", "Medio", "Fija movimiento de tierras y drenaje."),
    ("RC-03", "Certificado de intersección (SNAP / bosques protectores / patrimonio forestal)", "ARCONEL — UTA vía SUIA", "COA · RCOA · SUIA", 2, 1, 500, "RC-01", "No", "Bajo", "Automático en SUIA; probablemente gratuito (❓) — se mantienen 500 como holgura (D-L4)."),
    ("RC-04", "Registro Ambiental (FV > 1 y ≤ 10 MW) ante ARCONEL — Unidad Técnica Ambiental, vía SUIA; PMA/ficha del expediente", "ARCONEL — UTA (SUIA)", "Resol. ARCONEL-005/25 arts. 19–22 · Resol. MAATE-2025-0002-R · A.M. 083-B", 3, 6, 5000, "RC-03", "Sí", "Alto", "Tasa USD 180 (+80) + expediente (estimación, por confirmar); automático en la norma, 5–6 meses observados en otros sectores. Conservador: Licencia (arts. 23–35) si la «unidad de proyecto» supera 10 MW (P-06) — ver memo."),
    ("RC-06", "Certificado de altura (aeropuerto de Manta ~6 km): consulta caso por caso", "DGAC", "RDAC 154 Enmienda 3 (jun-2024)", 3, 2, 2000, "RC-01", "No", "Medio", "La RDAC 154 no exige estudio de deslumbramiento (Atlas K2)."),
    ("RC-07", "Descarte arqueológico (zona manteña)", "INPC", "Ley Orgánica de Cultura", 3, 3, 12000, "RC-01", "Parcial", "Medio-Alto", "Prospección antes del movimiento de tierras."),
    ("RC-08a", "Certificado de compatibilidad de uso de suelo y línea de fábrica", "GAD Montecristi", "COOTAD · LOOTUGS · PUGS", 4, 2, 3000, "RC-01", "No", "Medio", "Sin ficha pública en Montecristi (referencia: Manta); costo por confirmar."),
    ("RC-08b", "Cambio de uso de suelo rural (condicional: sólo si el predio es agrícola): informe MAG de no aptitud agropecuaria (90 días) + declaratoria del GAD", "GAD Montecristi · MAG", "LOTRTA art. 6 y 32 lit. l · Reglamento art. 3", 5, 4, 2000, "RC-08a", "No", "Medio-Alto", "Condicional a la clasificación del predio (P-07); costo por confirmar. Si no aplica, la ruta pasa directo a RC-08c."),
    ("RC-08c", "Permiso de construcción + visto bueno del Cuerpo de Bomberos", "GAD Montecristi · Bomberos", "COOTAD · Ordenanzas Montecristi", 9, 3, 5000, "RC-08a, RC-08b", "No", "Medio", "Tablas de Montecristi no públicas: costo por confirmar (referencia Manta: visto bueno con vigencia de 3 años). Holgura de 1 mes frente a RC-12."),
    ("RC-09", "Factibilidad de Conexión para autoabastecimiento (Cat. 2; estudios de flujos y estabilidad > 1 MW; carta a la máxima autoridad con proyectista registrado)", "CNEL EP U.N. Manabí", "005/24 arts. 12-16 · Código de Conexión", 7, 2, 15000, "RC-00, RC-14", "Sí", "Alto", "17-22 días normativos; vigencia 6 meses (art. 13) → la habilitación (RC-10) debe caer dentro de esa vigencia (control F12). Resuelve la duda #9."),
    ("RC-10", "Certificado de Habilitación (rubro USD 4/kW, tope 10.000); requiere arrendamiento/posesión notariada del predio", "CNEL EP", "005/24 arts. 14-15", 12, 1, 10000, "RC-09, RC-01", "Sí", "Medio", "≈ 18 días normativos. Expediente preparado durante la factibilidad. Obra según cronograma avalado (revocatoria art. 16)."),
    ("RC-11", "Importación y nacionalización (módulos, inversores, estructura, trafos): registro OCE, consulta arancelaria, INEN (USD 247 si aplica un RTE)", "SENAE · agente afianzado · INEN", "COPCI · Arancel · LRTI 55.19", 10, 5, 15000, "RC-00, RC-04", "Sí", "Medio", "Aranceles/ISD/IVA en 05_CAPEX (arancel 2026 por confirmar, P-03). Resolución anticipada de clasificación recomendable (P-04). Sin RTE obligatorio identificado para módulos."),
    ("RC-12", "Construcción y montaje (civil → hincado → módulos → BOS → CT/MT → conexión)", "Contratistas bajo gerencia Exergy", "—", 13, 7, 0, "RC-08c, RC-10, RC-11", "Sí", "Medio", "Costo en CAPEX. Drenaje antes de la temporada ene–abr."),
    ("RC-13", "Pruebas (5 días), medidor bidireccional MT (≤ 30 días), Contrato de Conexión (Anexo C), Contrato de Suministro y energización (COD)", "CNEL EP", "005/24 · ARCONEL-008/24", 20, 2, 12000, "RC-12", "Sí", "Bajo", "El Contrato de Suministro inicia el reloj de 24 meses del SEA (arts. 26-27)."),
    ("RC-14", "Ingeniería de detalle y owner's engineer (transversal); estudios eléctricos para RC-09", "Exergy / consultores", "—", 2, 10, 60000, "RC-02", "No", "Medio", "Parte del rubro 9 del CAPEX."),
    ("RC-15", "Servidumbre y derecho de vía de la línea 13,8 kV al punto de conexión (franja 6 m); permisos de cruce de vías", "CNEL EP · Prefectura de Manabí · MTOP · GAD", "ARCONEL-001/18 · normativa vial", 9, 4, 5000, "RC-01, RC-14", "No", "Medio", "Duración y costo por confirmar (estimación). ¿Resolución ministerial para línea privada o basta el diseño aprobado por CNEL? (❓, 02)."),
]
'''
old = block("TRAMITES = [", "\n\ndef build_tramites")
s = s.replace(old, NEW_TRAMITES.rstrip("\n"))
rep('calc(ws, r, 6, "=MAX(H8:H22)", fmt="0", bold=True)', 'calc(ws, r, 6, f"=MAX(H8:H{7 + len(TRAMITES)})", fmt="0", bold=True)')
rep('''        fit_row(ws, r, [(tr, 38, 9), (aut, 17, 8.5), (base, 17, 8.5), (nt, 32, 8.5)], min_h=18, pad=3)
        r += 1
    r1 = r - 1''',
    '''        fit_row(ws, r, [(tr, 38, 9), (aut, 17, 8.5), (base, 17, 8.5), (nt, 32, 8.5)], min_h=18, pad=3)
        if tid == "RC-09": name(wb, "Fin_RC09", S3, f"$H${r}")   # v3.1: vigencia de la factibilidad (control F12)
        if tid == "RC-10": name(wb, "Fin_RC10", S3, f"$H${r}")
        r += 1
    r1 = r - 1''')
rep('''    callout(ws, r, 4, 13, "Hitos binarios: RC-09 (capacidad del alimentador) y RC-04 (registro vs licencia). Si RC-04 deriva a licencia con consulta, el cronograma se ancla a 28–32 meses; si el alimentador no tiene capacidad → refuerzo de red a costo propio o redimensionar. Decreto Ejecutivo 32: el plazo (15-dic-2026) cae en el mes 3 → el proyecto se acredita ante CNEL/MAE como «en planificación/construcción» en los reportes mensuales.", height=40)
    ws.col_breaks.append(Break(id=13))   # página 1: tabla A..M · página 2: Gantt (B:C repetidas + N..AQ)''',
    '''    callout(ws, r, 4, 13, "Hitos binarios: RC-09 (capacidad del alimentador; pre-consulta escrita en RC-00) y RC-04 (Registro Ambiental ante ARCONEL; la Licencia es contingencia). La factibilidad vence a los 6 meses (005/24 art. 13): RC-10 debe caer dentro de esa vigencia (control F12). Decreto Ejecutivo 32: el plazo (18-dic-2026, RO Supl. 62) cae en el mes 3 → el proyecto se acredita ante CNEL/Viceministerio como «en curso» en los reportes mensuales.", height=40)
    r += 3
    # v3.1 (doc 18 D-L1 / D-L2): escenarios de cronograma NO recogidos por el motor (Fecha_COD y Meses_Construccion son globales) → memo estático
    section(ws, r, 2, 13, "Escenarios de cronograma — memo estático (sombra Python ≡ Motor, 08-sep-2026; recalcular si cambian las entradas)")
    r += 1
    for t in ["Caso Conservador ambiental (Licencia en vez de Registro): RC-04′ Licencia Ambiental meses 3–11 (9 meses, ≈ USD 60.000: EIA + consultor + tasa 1 ‰ + póliza 100 % del PMA) y RC-05 participación ciudadana meses 6–8 (≈ USD 10.000) → COD +3 meses (24). Efecto (Custom): TIR del proyecto sin cambio (el VAN se refiere al COD), TIR del accionista 18,5 % → 18,0 %, DSCR mínimo 0,731 → 0,723; Base: TIR 7,98 % → 7,90 %, accionista 10,9 % → 10,3 %.",
              "Retraso por red (refuerzos del alimentador, 6–18 meses según prensa; Manta al límite, CENACE 30-jun-2026): COD +12 meses (33 meses de construcción). Efecto (Custom): TIR del proyecto sin cambio (peaje 0 y escalación del CAPEX 0), TIR del accionista 18,5 % → 16,5 % (IDC), DSCR mínimo 0,731 → 0,701; Base (peaje 0,5 ¢ y +3 %/año): TIR 7,98 % → 7,69 %, accionista 10,9 % → 8,5 %. No incluye el costo de oportunidad del ahorro no percibido durante el retraso (≈ el ahorro del año 1 por cada 12 meses) ni el riesgo del D.E. 32. En el artefacto interactivo este escenario es un preset vivo.",
              "Nota: RC-05 (participación ciudadana) no existe en el caso Base porque el Registro Ambiental no la exige (por confirmar, Atlas N22); los IDs de los hitos se conservan para trazabilidad con las versiones anteriores."]:
        note(ws, r, 3, "• " + t, c2=13, size=8.5); fit_row(ws, r, [(t, 38 + 17 + 17 + 5 + 5 + 5 + 9 + 9 + 6 + 7 + 32, 8.5)], min_h=14); r += 1
    r -= 3
    ws.col_breaks.append(Break(id=13))   # página 1: tabla A..M · página 2: Gantt (B:C repetidas + N..AQ)''')
rep('''    setup_print(ws, landscape=True, scale=74, title_rows="6:7", title_cols="B:C", area=f"A1:{col(G0 + NM - 1)}{r}")   # 74 %: tabla y Gantt caben cada uno en una página''',
    '''    setup_print(ws, landscape=True, scale=74, title_rows="6:7", title_cols="B:C", area=f"A1:{col(G0 + NM - 1)}{r + 4}")   # 74 %: tabla y Gantt caben cada uno en una página''')
rep('sheet_header(ws, "3 · Trámites", "Ruta crítica a COD y costos de desarrollo: plazos normativos con holguras, dominada por lo ambiental y el alimentador. Edite inicio y duración (tinta); Mes_COD_Cron fija los meses de construcción de 08.", 3, last_col=13)',
    'sheet_header(ws, "3 · Trámites", "Ruta crítica a COD y costos de desarrollo (Base: Registro Ambiental ante ARCONEL; pre-consulta de capacidad; factibilidad en los meses 7–8 para no agotar su vigencia de 6 meses). Edite inicio y duración (tinta); Mes_COD_Cron fija los meses de construcción de 08. Plazos del Atlas Regulatorio v2.0 (08-sep-2026).", 3, last_col=13)')

# ------------------------------------------------------------------ 11_Riesgos · 15 riesgos
NEW_RIESGOS = '''RIESGOS = [
    ("Regulatorio", "Peaje de red para SGDA desde 28-feb-2029 (valor no publicado; por potencia y energía) erosiona el ahorro", 3, 3, "Sensibilidad 0–1,5 ¢/kWh y 0,5–1,0 $/kW-mes (10 §B); cláusula de reapertura en contratos; monitoreo de borradores ARCONEL; el alza tarifaria compensa parcialmente.", "Exergy (regulatorio)", "Borrador de regulación ARCONEL / consulta pública"),
    ("Técnico-regulatorio", "Alimentador 13,8 kV sin capacidad para 3,8 MWac: Manta entre las subestaciones al límite (CENACE vía Expreso, 30-jun-2026); refuerzos de 6–18 meses (Expreso, 20-ago-2026)", 3, 3, "Pre-consulta escrita de capacidad (RC-00) y factibilidad temprana (RC-09); alimentadores con margen; contingencia para refuerzos; producción ≤ demanda. Retraso de 12 meses: TIR del accionista 18,5 % → 16,5 % (Custom; memo estático de 03).", "Exergy (ingeniería)", "Respuesta de la pre-consulta / factibilidad"),
    ("Ambiental", "«Unidad de proyecto» (10,78 ha; 2 × 5 MWp) → Licencia Ambiental en vez de Registro ante ARCONEL (+3 meses, ≈ +70 k)", 2, 3, "Consulta de categorización a ARCONEL-UTA (SUIA); umbrales del CCAN (P-06); separar predios/plazos si conviene; Base = Registro (decisión D-L1); contingencia en el memo de 03.", "Exergy (permisos)", "Pronunciamiento de ARCONEL-UTA en SUIA"),
    ("Contractual", "Recaracterización del arriendo/O&M como venta encubierta de energía → revocatoria del certificado (sin precedentes públicos, P-11; la Ley 2026 legaliza a terceros)", 2, 3, "Renta fija indexada, nunca por kWh; arriendo en escritura separada; revisión previa de la Distribuidora (art. 8b); consulta DG 17.ª; abogado eléctrico. Probabilidad 2 por prudencia hasta la consulta (D-L8).", "Exergy (legal)", "Observaciones de CNEL al instrumento"),
    ("Comercial / regulatorio", "D.E. 32: SALELGI (AV1) sin autogeneración al 18-dic-2026 → desconexión en déficit / pérdida de tarifa preferente", 2, 3, "Notificar a CNEL/Viceministerio el proyecto en curso (reportes mensuales desde jul-2026); evaluar respaldo transitorio; documentar avance (pre-consulta, factibilidad, permisos).", "SALELGI + Exergy", "Oficios CNEL El Oro / MAE-VEER"),
    ("Mercado", "CAPEX real > base (módulos +30 % desde dic-2025; estructura ZM con arancel 20 %; trafos con lead time largo; arancel 2026 no cotejado, P-03)", 2, 2, "3 cotizaciones (EPC llave en mano vs multi-contrato); fijar precio de módulos con ventana; contingencia 6 %; caso Conservador +15 % y +5 %/año.", "Exergy (procura)", "Cotizaciones firmes vs 05_CAPEX"),
    ("Tarifario / político", "Cambio del pliego o de subsidios (déficit 2026 USD 621,9 M): la tarifa evitable puede subir o bajar", 2, 2, "Escenarios ±15 % y escalación 0–3 %; el alza favorece el ahorro; diversificar valor (I-REC, Alcance 2).", "Exergy", "Resoluciones ARCONEL anuales (nov-dic)"),
    ("Fiscal", "Deducción adicional no aplicable: certificación ambiental previa (RLRTI 28.6.g) no obtenible o tardía (procedimiento no publicado, P-01); IVA 0 % «accesorios» más restrictivo (P-04)", 2, 3, f'="Solicitar la certificación a ARCONEL-UTA antes de la primera declaración; consulta vinculante SRI; resolución anticipada SENAE. Cuantificado en el tornado (10 §B): sin deducción, TIR "&TEXT({mo(T_DEDAD, "TIR")},"0.0%")&" frente a "&TEXT(X_TIR,"0.0%")&"; accionista "&TEXT({mo(T_DEDAD, "TIR_eq")},"0.0%")&" frente a "&TEXT(X_TIReq,"0.0%")&"."', "SALELGI (tributario) + Exergy (permisos)", "Certificación ARCONEL / absolución SRI"),
    ("Financiero", '="DSCR mínimo "&TEXT(P50_DSCR,"0.00")&"x en t = "&Anio_DSCR_Min&" con "&Plazo_Deuda&" años / "&TEXT(Pct_Apalancamiento,"0%")&" (objetivo "&TEXT(DSCR_Objetivo,"0.00")&"x)"', 3, 2, "Plazo 10 años (alineado con la depreciación fiscal; a 12 años el DSCR cae tras el año 10) o apalancamiento 50–60 %; período de gracia; cuenta de reserva; líneas verdes (BanEcuador 11,86 %; Produbanco hasta 84 meses).", "SALELGI (finanzas)", "Term sheet bancario"),
    ("Operativo", "Soiling (6–7 meses secos, garúa), corrosión C3/C4, seguridad física", 2, 1, "Limpieza 3–4/año en el fee de O&M; estructura ZM275+ e inversores C5; seguridad 24/7 incluida.", "Exergy (O&M)", "PR mensual vs 82,5 %"),
    ("Cronograma", "Retrasos: Registro Ambiental «meses en la práctica» (5–6), permisos municipales sin fichas públicas, cambio de uso de suelo rural (90 días MAG), importación/aduana (INEN, clasificación), lluvias ene–abr", 2, 2, "Expediente de habilitación preparado durante la factibilidad (vigencia 6 meses, control F12); resolución anticipada de clasificación; agente afianzado; drenaje antes de la temporada; holguras en RC-08c y RC-15.", "Exergy (gerencia)", "Hitos RC-04 / RC-08 / RC-11 / RC-12"),
    ("Regulatorio", "Cambio regulatorio antes de operar: más de seis hitos legales entre 2021 y 2026; el patrón amplía la participación privada", 3, 2, "La Disp. Transitoria Única de la 005/24 protege lo otorgado; obtener el Certificado de Habilitación cuanto antes; monitoreo trimestral de ARCONEL (Atlas).", "Exergy (regulatorio)", "Borradores ARCONEL / Registro Oficial"),
    ("Regulatorio", "Vacío reglamentario y litigio constitucional de la Ley 2026 (14 demandas, 1 admitida): régimen de excedentes remitido al reglamento", 2, 2, "El modelo no depende de excedentes (art. 9: producción ≤ demanda) ni de la Ley 2026 (encaje en la 005/24 + LOCE 2024); monitoreo (P-13).", "Exergy (legal)", "Sentencia CC / reglamento de la Ley 2026"),
    ("Institucional", "Inestabilidad institucional: dos ministros en 20 meses, fusión Ambiente-Energía, ARCONEL con director encargado y nuevo rol ambiental", 2, 2, "Trámites por escrito y con acuse; expedientes completos; no depender de criterios verbales; consulta DG 17.ª para casos especiales.", "Exergy (permisos)", "Cambios de autoridades / reorganizaciones"),
    ("Fiscal (Exergy)", "IVA de Exergy no recuperable por proporcionalidad (art. 66) si mezcla ventas gravadas y 0 %; precios de transferencia con SALELGI; retenciones 2026 (2 / 5 / 10 %) como anticipo", 2, 2, "Facturar bienes 0 % y servicios 15 % por separado; estudio de comparables (fee, O&M, arriendo); planificar la caja de las retenciones. Interno: no afecta el flujo de SALELGI.", "Exergy (tributario)", "Declaraciones de IVA / Anexo OPR"),
]
'''
old = block("RIESGOS = [", "\n\ndef build_riesgos")
s = s.replace(old, NEW_RIESGOS.rstrip("\n"))
rep('sheet_header(ws, "11 · Matriz de riesgos", "Probabilidad × impacto (1–3 en cada eje; umbrales en 01 §J), mitigación, dueño y alerta temprana. Los tres primeros riesgos dominan la decisión; los de mercado y financiero se cuantifican en 10.", 11, last_col=10)',
    'sheet_header(ws, "11 · Matriz de riesgos", "Probabilidad × impacto (1–3 en cada eje; umbrales en 01 §I), mitigación, dueño y alerta temprana. Peaje, red y fiscal (certificación de la deducción) dominan la decisión; los de mercado, fiscal y financiero se cuantifican en 10. Conciliada con el Atlas Regulatorio v2.0 (08-sep-2026).", 11, last_col=10)')

# ------------------------------------------------------------------ 12_Fuentes
rep('("Regulación ARCONEL-005/24 codificada (Res. ARCONEL-010/2024), PDF oficial — arts. 6, 8, 9, 10, 25, 27, 28, Disp. Gral. Décima (leído 01-sep-2026).",',
    '("Regulación ARCONEL-005/24 codificada (Res. ARCONEL-010/2024), PDF oficial — arts. 5.17, 6, 7, 8, 9, 10, 12–16, 25, 27, 28, Disp. Gral. Décima y 17.ª, Disp. Trans. Cuarta (leído 01-sep-2026; verbatim cotejados por la Auditoría Fases 1–2, 07-sep-2026).",')
rep('("Reglamento LOCE — D.E. 176 (RO 28-feb-2024), arts. 5 y 24 (peaje de distribución; cargos por uso o disponibilidad de la red) — PDF SRI (01-sep-2026).",',
    '("Reglamento LOCE — D.E. 176 (RO 28-feb-2024): art. 18 y DT 16.ª (peajes SGDA; arts. 5 y 24 por verificar), art. 78 → RLRTI art. 28 num. 6 lit. g (certificación ambiental previa para la deducción adicional) — PDF SRI (01-sep-2026; Atlas N20).",')
rep('("Decreto Ejecutivo 32 (15-jun-2025; RO Supl. 62, 18-jun-2025): PBP Law; El Universo (jun-2025); Expreso (22-jul y 20-ago-2026); El Oriente (24-jul-2026); DMEGC Solar LATAM (01-sep-2026).",',
    '("Decreto Ejecutivo 32 (15-jun-2025; RO Supl. 62, 18-jun-2025; DT 14.ª: 18 meses → 18-dic-2026): PBP Law; El Universo (jun-2025); Expreso (22/23-jul y 20-ago-2026: seguimiento mensual del Viceministerio); El Oriente (24-jul-2026); DMEGC Solar LATAM (01-sep-2026).",')
rep('("BCE — tasas máximas mar-2026 (VerifacturaEC): Corporativo 9,33 %, Empresarial 10,21 %, PYMES 11,83 %; Primicias (05-ago-2026): efectiva promedio corporativo 6,74 % (jun-2026).", "https://www.primicias.ec/economia/tasas-interes-ecuador-reduccion-creditos-prestamos-bancos-129529/"),',
    '("BCE — tasas referenciales ago-2026 (Atlas J): corporativo 6,79 % · empresarial 8,62 % · PYME 9,18 %; máximas mar-2026 (VerifacturaEC): corporativo 9,33 %, empresarial 10,21 %, PYMES 11,83 %; Primicias (05-ago-2026): efectiva promedio corporativo 6,74 % (jun-2026). Financiamiento verde: BanEcuador 11,86 % (PYME, ≤ USD 3 MM, 60 meses, 6 de gracia), Produbanco Líneas Verdes hasta 84 meses; riesgo país 386 pb (12-jun-2026); S&P B (14-ago-2026).", "https://www.primicias.ec/economia/tasas-interes-ecuador-reduccion-creditos-prestamos-bancos-129529/"),')
rep('''    ("01 H4: precios de módulos > +30 % desde dic-2025 (OPIS/pv magazine, 28-ago-2026) → escalación del CAPEX 3 %/año Base · 5 % Conservador · 0 % Favorable hasta la compra (2027–28); índice por confirmar.", None),
]''',
    '''    ("01 H4: precios de módulos > +30 % desde dic-2025 (OPIS/pv magazine, 28-ago-2026) → escalación del CAPEX 3 %/año Base · 5 % Conservador · 0 % Favorable hasta la compra (2027–28); índice por confirmar.", None),
    # v3.1 (actualización legal, doc 18): Proyecto «Marco Legal FV Ecuador — Exergy»
    ("Atlas Regulatorio FV Ecuador v2.0 — Exergy (Proyecto «Marco Legal FV Ecuador», claude.ai; sello 08-sep-2026 con pasada adversarial): 32 normas con vigencia y cadena, 16 hitos de permisos, 24 conceptos fiscales, 24 pendientes (P-01…P-14, D-01…D-11), 18 correcciones, 45 fuentes primarias. Base de la conciliación legal v3.1 (doc 18, 08-sep-2026).", "https://claude.ai/code/artifact/a807297c-b6d9-4df8-a041-fbabd8dc70c4"),
    ("Informe Fase 3 v1.1 — Fiscal, financiamiento, permisos y riesgos (07/08-sep-2026; errata: el tope del 5 % subsiste) e Informe de Auditoría Fases 1–2 (92 filas verificadas contra fuentes primarias, 07-sep-2026), Proyecto «Marco Legal FV Ecuador — Exergy».", None),
    ("Ley Orgánica para el Fortalecimiento de los Sectores Estratégicos de Minería y Energía (RO 5.º Supl. 234, 02-mar-2026): arts. 23 (art. innumerado tras el 44 LOSPEE), 33 y 48; vigente-no-operativa; litigio constitucional 14 demandas / 1 admitida (El Universo, 06-jun-2026). Sentencia CC 112-21-IN/25 (11-dic-2025).", None),
    ("Resol. ARCONEL-005/25 — Procedimiento para la regularización, prevención, control y seguimiento ambiental de actividades eléctricas (RO Supl. 67, 25-jun-2025): arts. 19–22 Registro Ambiental (FV > 1 ≤ 10 MW), 23–35 Licencia; Resol. MAATE-2025-0002-R (22-abr-2025): ARCONEL como Autoridad Ambiental Competente del sector eléctrico; A.M. 083-B (tasa USD 180).", None),
    ("Regulación ARCONEL-008/24 (Resol. 015/2024, 15-nov-2024) — prestación del servicio de distribución y comercialización (sucede a la 001/20: medición) y ARCONEL-009/24 (calidad, codificada); ARCONEL-006/24 (Resol. 011/2024, 27-oct-2024) deroga la 002/21.", None),
    ("Resol. SRI NAC-DGERCGC26-00000009 (27-feb-2026; vigente 01-mar-2026) — porcentajes de retención en la fuente 2026 (obra 2 % · servicios de sociedades 5 % · arriendo 10 % · bienes 2 %). LRTI art. 65 (IVA 15 %), art. 55 num. 19 (0 % FV), art. 10 num. 7 (deducción adicional, tope 5 %), art. 11 (arrastre de pérdidas).", None),
    ("SENAE — boletín 15-ene-2024: código Ecuapass 0719 para bienes con IVA 0 % «paneles solares y accesorios para la generación solar FV»; COMEX 002-2025 (0 % temporal) vencida el 31-dic-2025 sin prórroga localizada; ISD 2026: D.E. 272 y Acuerdo MPCEI-2026-0003-A (tarifas diferenciadas sin partidas FV); RAISD art. 17.1 (exención con contrato de inversión).", None),
    ("LOTRTA art. 6 y 32 lit. l; Reglamento art. 3 — cambio de uso de suelo rural (informe MAG en 90 días, lo solicita el GAD). Regulación ARCONEL-001/18 — franjas de servidumbre (6 m a ≤ 13,8 kV). RDAC 154 Enmienda 3 (jun-2024) — consulta de altura DGAC, sin estudio de deslumbramiento.", None),
    ("Prensa verificada por el Atlas: Expreso 30-jun-2026 (CENACE: subestaciones al límite, Manta; 643 MW privados contenidos) · Expreso 20-ago-2026 (refuerzos de red 6–18 meses) · Expreso 23-jul-2026 (seguimiento mensual del D.E. 32) · El Universo 06-jun-2026 (litigio de la Ley 2026).", None),
]''')
rep('''    "Utilidad_Gravable_SALELGI": "dato P3 (contabilidad de SALELGI): utilidad gravable disponible para absorber pérdidas incrementales; vacío = ilimitada.",
}''',
    '''    "Utilidad_Gravable_SALELGI": "dato P3 (contabilidad de SALELGI): utilidad gravable disponible para absorber pérdidas incrementales; vacío = ilimitada.",
    # v3.1 (doc 18 D-L6)
    "Aplica_DedAd": "certificación ambiental previa exigida por el RLRTI art. 28 num. 6 lit. g (procedimiento no publicado, Atlas P-01); Sí en el Base; el tornado (10 §B) muestra el caso sin deducción.",
}''')
rep('''    out.append("Además (no contados): aranceles inversores 5 % / trafos 10 % — verificar en el arancel en vivo SENAE (Ecuapass); demanda promedio 2.200 kW y FGD 0,956 (sólo para la factura de referencia).")
    return out''',
    '''    out.append("Además (no contados): aranceles 2026 de inversores 5 % / estructura 20 % / trafos 10 % — no cotejados en 2026 (Atlas P-03; COMEX 002-2025 vencida el 31-dic-2025); demanda promedio 2.200 kW y FGD 0,956 (sólo para la factura de referencia).")
    out.append("Pendientes legales del Atlas Regulatorio v2.0 (no son entradas del modelo y no cuentan en N_Por_Confirmar; detalle en 02 zonas grises): P-01 certificación ambiental de la deducción · P-02 techo de gasto tributario 2026 · P-03 arancel 2026 · P-04 alcance del IVA 0 % · P-06 umbrales del CCAN en SUIA · P-07 uso de suelo del predio · P-08 capacidad remanente del alimentador · P-09 textos ilegibles · P-11 precedentes de recaracterización · P-12 figura inscribible · P-13 litigio de la Ley 2026 · P-14 exceso sobre el tope.")
    return out''')
rep('''              "No se modela la segunda planta de 5 MWp ni la venta de I-REC (argumento comercial: ≈ 1.550 tCO₂e/año de Alcance 2 con factor 0,12 tCO₂/MWh — estimación)."]:''',
    '''              "No se modela la segunda planta de 5 MWp ni la venta de I-REC (argumento comercial: ≈ 1.550 tCO₂e/año de Alcance 2 con factor 0,12 tCO₂/MWh — estimación).",
              "v3.1 · Deducción adicional condicionada: Aplica_DedAd (Sí/No) multiplica la deducción en 07 (DedAd_Anual) y en el Motor (fila «Deducción adicional aplicable»); el tornado incluye el caso alterno (barra 15). Permiso ambiental: 03 y el rubro 9 asumen Registro Ambiental ante ARCONEL; la Licencia y el retraso por red se documentan como memo estático en 03 (calculado con la sombra, no con el motor: Fecha_COD y Meses_Construccion son globales) y como riesgos en 11. El IVA del rubro 9 (12 %) es 15 % sobre ≈ 80 % de servicios gravados."]:''')
rep('''Base realista moderado (98 % · 3 %/año · reemplazo SALELGI en t = 13 · 21 meses · tasa del accionista 12 %) con la definición v2.0 reproducible en neutro. Elaborado por Claude''',
    '''Base realista moderado (98 % · 3 %/año · reemplazo SALELGI en t = 13 · 21 meses · tasa del accionista 12 %) con la definición v2.0 reproducible en neutro · v3.1 (08-sep-2026) actualización legal conciliada con el Atlas Regulatorio FV Ecuador v2.0 (doc 18): 02 con 25 normas (Ley 2026, Sentencia CC, retenciones 2026, suelo rural, servidumbres; ARCONEL como autoridad ambiental; D.E. 32 al 18-dic-2026; medición 008/24; cifras en fórmula) y 15 zonas grises con los pendientes P-xx; 03 con Registro Ambiental, pre-consulta de capacidad, factibilidad en los meses 7–8 (vigencia 6 meses, control F12), RC-08a/b/c, RC-15 y memo estático de escenarios; 11 con 15 riesgos (red ↑, certificación de la deducción); 12 con las fuentes del Atlas y BCE ago-2026; Motor con el parámetro «deducción adicional aplicable» (caso 111 «Sin deducción adicional», barra 15 del tornado, control H14); Custom con los diez valores fijados por Jorge el 04-sep-2026 (SALELGI compra el terreno, peaje 0, tarifa +2 %/año, disponibilidad 97 %, escalación del CAPEX 0, degradación 1 %/año, fee O&M 16, OPEX +2 %/año, deuda 100 % al 7,5 %); Meses_Construccion vuelve a leer Mes_COD_Cron. Elaborado por Claude''')

# ------------------------------------------------------------------ 13_Controles · F12 y H14
rep('''        ("F11", "Cero errores en los KPI principales", '=IF(ISERROR(VAN_Proyecto+VAN_Equity+VAN_Exergy+P90_VAN+C_VAN+B_VAN+F_VAN),"■ error","● ok")'),''',
    '''        ("F11", "Cero errores en los KPI principales", '=IF(ISERROR(VAN_Proyecto+VAN_Equity+VAN_Exergy+P90_VAN+C_VAN+B_VAN+F_VAN),"■ error","● ok")'),
        ("F12", "Vigencia de la Factibilidad de Conexión (6 meses, 005/24 art. 13): el Certificado de Habilitación (RC-10) termina ≤ 6 meses después de la factibilidad (RC-09)", '=IF(Fin_RC10-Fin_RC09<=6,"● ok ("&(Fin_RC10-Fin_RC09)&" meses)","■ "&(Fin_RC10-Fin_RC09)&" meses > 6: la factibilidad vence antes de la habilitación — reordenar 03")'),''')
rep('''        ("H9", "Bloque B · escalación del CAPEX entre 0 y 15 %/año en los cuatro casos; Fecha_Precios ≤ Fecha_COD", '=IF(AND(MIN(Esc_Escalacion_CAPEX)>=0,MAX(Esc_Escalacion_CAPEX)<=0.15,Fecha_Precios<=Fecha_COD),"● ok","■ escalación fuera de 0–15 % o fecha de precios posterior al COD")'),''',
    '''        ("H9", "Bloque B · escalación del CAPEX entre 0 y 15 %/año en los cuatro casos; Fecha_Precios ≤ Fecha_COD", '=IF(AND(MIN(Esc_Escalacion_CAPEX)>=0,MAX(Esc_Escalacion_CAPEX)<=0.15,Fecha_Precios<=Fecha_COD),"● ok","■ escalación fuera de 0–15 % o fecha de precios posterior al COD")'),
        ("H14", "Deducción adicional aplicable (v3.1): Motor DedAd (Custom) ≡ 07 DedAd_Anual; el caso «Sin deducción adicional» tiene DedAd = 0 si Aplica_DedAd = Sí (y la deducción completa si es No)", ok1(f'ABS({SM_}$B${SCAL_ROWS["DedAd"]}-DedAd_Anual)+ABS({SM_}${mcol(T_DEDAD)}${SCAL_ROWS["DedAd"]}-IF(Aplica_DedAd="Sí",0,MIN(CAPEX_Depreciable*Pct_Elegible_DedAd/Vida_Fiscal_Equipos,Tope_DedAd_Pct*Ingresos_SALELGI)))')),''')
rep('sheet_header(ws, "13 · Controles", "Único control de calidad: identidades contables, candados regulatorios y de rango (A–F), casos (G), ronda 2 (H) y libro (I). Todo debe estar en ●; ■ = inconsistencia o entrada fuera de rango; la portada lee el contador.", 13, last_col=6, total=NSHEETS)',
    'sheet_header(ws, "13 · Controles", "Único control de calidad: identidades contables, candados regulatorios y de rango (A–F, incl. F12 vigencia de la factibilidad), casos (G), ronda 2 y v3.1 (H) y libro (I). Todo debe estar en ●; ■ = inconsistencia o entrada fuera de rango; la portada lee el contador.", 13, last_col=6, total=NSHEETS)')

open(P, "w", encoding="utf-8").write(s)
print("patch_content_v31: ok")
